### ISSUE TITLE
Custom routes URL prefix

### ISSUE THREAD

**Issue by karbyshevds** [odahu/odahu-flow#510]
Custom routes are not validated now so user can create any route. But the only allowed prefix is `/custom` which is not documented anywhere and route can be created but will not work.

The resolution is to change it to value and pass it as a param to odahu-flow helm chart and ODAHU config itself.

- [x] Add `customRoutePrefix` variable to ODAHU config (`deployment` section)
- [x] Add route validation: url prefix must start with value of `customRoutePrefix` from ODAHU config
- [x] Define customRoutePrefix (defaults to `/custom`) in Helm Values. Section: `config.deployment`
- [x] Pass `customRoutePrefix` from Helm values to Ingress spec `/helms/odahu-flow-core/templates/edge-ingress.yaml` (instead of hardcoded `/custom`)

**Comment by BPylypenko** [comment]
As far as I understood, the task here was to:
1. add validation for `customRoutePrefix`
2. user can use different values ​​for `customRoutePrefix`.

And due to the fact that it is hardcoded [here]( https://github.com/odahu/odahu-flow/pull/643/files#diff-2f87765f24535e50cf6761d56c2360186fe3f554c84aae7a1bb80346d7bd75c2R100 ), it turns out that it only works with `/custom`.


The `customRoutePrefix` value is used by [this file](https://github.com/odahu/odahu-flow/blob/510-custom-routes-validation-fix/helms/odahu-flow-core/templates/edge-ingress.yaml#L24) to create one of the paths in the ingres manifest in the Istio namespace for Istio. Everything is OK here, we can specify our path through a variable and it will use it.

The problem is that the logic in [the file](https://github.com/odahu/odahu-flow/pull/643/files#diff-2f87765f24535e50cf6761d56c2360186fe3f554c84aae7a1bb80346d7bd75c2R100) is not passed through a variable, so whatever we pass in the config for Istio, logic won't care as it only wants the `/custom` path.

As @lev-titov said, he thought the task was only the 1st point (add validation for `customRoutePrefix`).
So we have to discuss this in the daily meeting and decide how to handle the challenge.
